var centrosFuncionais = {
    "AJU IT MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BHE CA AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BHE ES AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BHE ES GR":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BHE ES MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BHE ES MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BHE ES RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BLM GR MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BLM QB AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BLM QB FO":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BLM QB MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BNU AB AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BNU AB MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BR LIC GR":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "BRE AG AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BRE AG MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BRE AG MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BRU AL AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BRU AL MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BRU AL RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BSA SU FO":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "BSA SU MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "BVA AB AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BVA AB MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BVA AB MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "BVA AB ST":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CAS BC AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CAS BC GR":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "CAS BC MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CAS BC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CAS BC RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CAS VP MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CBA MC MD":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "CBA MC MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "CCO JL AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CMA FM MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CPE CM MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CPE CM MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CPS CL MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CSC DC AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CSC DC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CSL VS MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA ACEFO":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA IMPMT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA JR AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA MC AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA MC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA MR AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA MR FO":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA MR MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA TF AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CTA TF MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "CUA SV AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "DOS CS MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FLA PV AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FLA PV MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FLA PV MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FNS ACEFO":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FNS IMPMT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FNS PO AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FNS PO FO":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FNS PO MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FNS PO MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FOZ AI AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FOZ AI MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "FSA GV MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "GNA GR MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "GNA RD FO":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "GNA RD MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "GTBXGS MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "GTBXGS ST":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "GUR BR MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "GVS JK MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "IAI GM AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "ILH AP MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "ITZ RC AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "ITZ RC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "JFA JC AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "JFA JC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "JIP PV MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "JNE JP MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "JPA TR MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "JVE LN AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "JVE LN MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "LDA PR AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "LDA PR MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "LGS CC AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "LGS CC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MBA QE MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MCO MS MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MGA NM AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MGA NM MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MNS EM MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MNS LM AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MNS LM MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MNS LM MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MNS LM ST":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MOSQST ST":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MPA GG AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "MPA GG MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "NHO LO MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "NTL JU AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "NTL JU MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "NTL JU MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "OCO SA AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "OCO SA MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE BV AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE BV MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE BV MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE BV RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE DESAT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE GA AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE IMPAT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE IMPMT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE LX MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE MF MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAE MF MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PAS CC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PGO RB AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PGO RB MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PGU BR MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PLT QN MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PMJ SO FO":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PMJ SO MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PNG GL AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PPE CM AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PPE CM MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PPE CM RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PTA PL MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PVO FQ MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "PVO FQ MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "RBO RB MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "RBO RB MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "RCE AM AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "RCE AM MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "RJO AC MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "RJO AM AT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "RJO AM MD":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "RJO AM MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "RJO CO MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "RJO DD GR":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "RJO EN MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "ROI MD RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "RPO TB AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "RPO TB MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "RPO TB RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SAN AN MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SCR EA MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SDR IT MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SDR RC MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SDR RC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SJC EB AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SJC EB MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SLS US AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SLS US MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SLS US MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SMA AN MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SNE JC AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SNE JC FB":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SNE JC FO":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SNE JC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SOC PH AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SOC PH MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SOC PH RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",

    "SPO ADM45":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO ADMGR":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO ADMMT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO BG AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO DD GR": "Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO EI AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO EI MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO IG 45":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO IG AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO IG FO":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO IG GR":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO IG MD":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO IG MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO LP AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO LP MD":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO LP MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO MB AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO MB MD":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO MB MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO PH AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SPO PH MD":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO PH MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO PPCMD":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "SPO VE MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",

    "SRM SP MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SRR QN AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SRR QN MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "SRR QN RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "STS WL AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "STS WL MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "STS WL MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "STS WL RD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "TANGBR MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "TLS ES MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "TSA AN AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "TSA AN MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "TTE SC MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "UGN QN MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "ULA MA AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "ULA MA MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "URA FR MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "VCA TN MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "VGA TG MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "VGA TG MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "VRD SC MT":"Precisa executar ANTES de enviar para agendamento (ou estar com PEND EXT: 10, 11, 19, 21, 23 ou 42)",
    "VTA JM AT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "VTA JM MD":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade.",
    "VTA JM MT":"Enviar para agendamento. Pois centro funcional será executado após a conclusão da atividade."
};

function buscarEstacao() {
var sigla = document.getElementById("sigla").value.toUpperCase().trim(); // Obtém a sigla inserida pelo usuário em letras maiúsculas
var estacaoLabel = document.getElementById("resultado"); // Obtém o elemento HTML onde será exibido o resultado

// Verifica se a sigla existe no dicionário
if (centrosFuncionais.hasOwnProperty(sigla)) {
var estacao = centrosFuncionais[sigla]; // Obtém o nome da estação correspondente à sigla
estacaoLabel.textContent = estacao; // Exibe o resultado no elemento HTML
} else {
estacaoLabel.textContent = "Sigla não encontrada"; // Exibe mensagem de erro caso a sigla não seja encontrada
}
}

function limparDados() {
document.getElementById("sigla").value = ""; // Limpa o campo de input
document.getElementById("resultado").textContent = ""; // Limpa o resultado anterior
}

document.getElementById("sigla").addEventListener("keydown", function(event) {
if (event.key === "Enter") {
event.preventDefault(); // Impede o comportamento padrão do Enter de inserir uma quebra de linha
buscarEstacao();
}
});

document.addEventListener("keydown", function(event) {
if (event.key === "Escape") {
event.preventDefault(); // Impede o comportamento padrão do ESC de fechar a janela
limparDados();
}
});
